import type { Metadata } from "next";
import { Mulish } from "next/font/google";

import "./globals.css";

const mulishSans = Mulish({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-mulish-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${mulishSans.variable} dark antialiased`}>
        {children}
      </body>
    </html>
  );
}
